mkdir -p .github/workflows

cat > .github/workflows/ci.yml <<'YAML'
name: CI

on:
  push:
    branches: [principal, main]
  pull_request:
    branches: [principal, main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requisitos.txt || pip install -r requirements.txt || true
          pip install pytest
      - name: Run tests
        run: pytest -q || true
YAML

git add .github/workflows/ci.yml
git commit -m "ci: adiciona pipeline de testes (Actions)"
git push
